name: Jupyter Sidebar Chatbot Release Pipeline

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install build twine
        npm ci
        cd jupyter-lab-extension && npm ci
    
    - name: Build extension
      run: |
        cd jupyter-lab-extension && npm run build
    
    - name: Build Python package
      run: |
        python -m build backend/
    
    - name: Publish Python package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: backend/dist/
        password: ${{ secrets.PYPI_API_TOKEN }}
        skip-existing: true
    
    - name: Publish npm package
      run: |
        cd jupyter-lab-extension && npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
